### ISSUE TITLE
Can't open PR as non-collaborator anymore

### ISSUE THREAD

**Issue by hassila** [apple/swift-lmdb#4]
Hi, I wanted to open a PR similar to #2 as there are two macOS/Apple Silicon fixes that we'd want to bring over - if you could open the repo for PR:s again I'll put one together and run the DocC test suite as last time.

Specifically we'd want to merge
https://github.com/apple/swift-lmdb/commit/6a1954d0ae6876b70f503121483a1c5107a910c2
and
https://github.com/apple/swift-lmdb/commit/b53474758f4fbcca2e76031017bbddfe92474e30

Ping @franklinsch

**Comment by hassila** [comment]
<img width="511" alt="image" src="https://github.com/apple/swift-lmdb/assets/8501048/c255c583-8ff6-406d-9a08-d39a95417343">

**Comment by hassila** [comment]
@FranzBusch - sorry for disturbing, do you have ability to fix the permissions? We'd like to do the PR as one of those commits fixes running with ASAN for us...

**Comment by franklinsch** [comment]
Hi @hassila, the permissions should allow you open a PR. Are you opening a PR from the GitHub UI in this repo, or your fork?

**Comment by hassila** [comment]
From the Github ui in this repo, I can try from my fork instead.

**Comment by hassila** [comment]
But its a bit weird, I am quite sure I opened #2 from the GitHub UI here...

**Comment by hassila** [comment]
Ok, I must have been confused, thanks - I have opened https://github.com/apple/swift-lmdb/pull/5 now, will run test suite on it.
